services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vehicle-api
    restart: always
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/vehicle-database
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
